### ISSUE TITLE
Exception thrown after upgrading AutoMapper: Method not found: 'Void AutoMapper.IMapperConfigurationExpression.set_CreateMissingTypeMaps(Boolean)'

### ISSUE THREAD

**Issue by fhls** [eWAYPayment/eway-rapid-net#28]
Hello

We are using eWAY to process payment in our system. However the API stops working and throw exception after we upgrade the AutoMapper plugin to 6.0.2:

Method not found: 'Void AutoMapper.IMapperConfigurationExpression.set_CreateMissingTypeMaps(Boolean)'

Stack Trace:    at eWAY.Rapid.Internals.Services.MappingService.<>c.<RegisterMapping>b__4_0(IMapperConfigurationExpression cfg)
   at AutoMapper.MapperConfiguration.Build(Action`1 configure)
   at AutoMapper.Mapper.Initialize(Action`1 config)
   at eWAY.Rapid.Internals.Services.MappingService.RegisterMapping() in C:\test_net\eway-rapid-net\eWAY.Rapid\Internals\Services\MappingService.cs:line 34
   at eWAY.Rapid.RapidClientFactory.NewRapidClient(String apiKey, String password, String rapidEndpoint) in C:\test_net\eway-rapid-net\eWAY.Rapid\RapidClientFactory.cs:line 23

I think it may because we also use static API to initial Automapper in our system and that has some conflicts with eWAY dll. I upgraded eWAY to 1.6.0 beta and the issue still exists.

Regards

**Comment by incarnate** [comment]
Hi @fhls - we've just released version 1.6.0 which uses AutoMapper 6.2, does the same issue still occur?

**Comment by fhls** [comment]
@incarnate we upgrade to 1.6.0 and it is working now, thank you for that update.

**Comment by incarnate** [comment]
Thanks for confirming @fhls
